knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            page-size: A4
            orientation: portrait
            dpi: 300

