twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
      # point this wherever your css files live
      '%kernel.project_dir%/public/css': styles
      '%kernel.project_dir%/public/img': img

when@test:
    twig:
        strict_variables: true
