controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api/v1

secure_controllers:
    resource: ../../src/Controller/Secure
    type: annotation
    prefix: /api/v1/secure

kernel:
    resource: ../../src/Kernel.php
    type: annotation
