<?php /** @noinspection SpellCheckingInspection */

namespace App\Helpers;

trait CountriesTrait
{

    /**
     * @return \string[][]
     */
    public function getCountries(): array
    {
        return [
            [
                'iso' => 'europa',
                'name' => 'Europa',
                'countries' => [
                    ["iso" => "AL", "name" => "Albania"],
                    ["iso" => "DE", "name" => "Alemania"],
                    ["iso" => "AD", "name" => "Andorra"],
                    ["iso" => "AM", "name" => "Armenia"],
                    ["iso" => "AT", "name" => "Austria"],
                    ["iso" => "AZ", "name" => "Azerbaiyán"],
                    ["iso" => "BE", "name" => "Bélgica"],
                    ["iso" => "BY", "name" => "Bielorrusia"],
                    ["iso" => "BA", "name" => "Bosnia y Herzegovina"],
                    ["iso" => "BG", "name" => "Bulgaria"],
                    ["iso" => "CY", "name" => "Chipre"],
                    ["iso" => "VA", "name" => "Ciudad del Vaticano (Santa Sede)"],
                    ["iso" => "HR", "name" => "Croacia"],
                    ["iso" => "DK", "name" => "Dinamarca"],
                    ["iso" => "SK", "name" => "Eslovaquia"],
                    ["iso" => "SI", "name" => "Eslovenia"],
                    ["iso" => "ES", "name" => "España"],
                    ["iso" => "EE", "name" => "Estonia"],
                    ["iso" => "FI", "name" => "Finlandia"],
                    ["iso" => "FR", "name" => "Francia"],
                    ["iso" => "GE", "name" => "Georgia"],
                    ["iso" => "GR", "name" => "Grecia"],
                    ["iso" => "HU", "name" => "Hungría"],
                    ["iso" => "IE", "name" => "Irlanda"],
                    ["iso" => "IS", "name" => "Islandia"],
                    ["iso" => "IT", "name" => "Italia"],
                    ["iso" => "XK", "name" => "Kosovo"],
                    ["iso" => "LV", "name" => "Letonia"],
                    ["iso" => "LI", "name" => "Liechtenstein"],
                    ["iso" => "LT", "name" => "Lituania"],
                    ["iso" => "LU", "name" => "Luxemburgo"],
                    ["iso" => "MK", "name" => "Macedonia, República de"],
                    ["iso" => "MT", "name" => "Malta"],
                    ["iso" => "MD", "name" => "Moldavia"],
                    ["iso" => "MC", "name" => "Mónaco"],
                    ["iso" => "ME", "name" => "Montenegro"],
                    ["iso" => "NO", "name" => "Noruega"],
                    ["iso" => "NL", "name" => "Países Bajos"],
                    ["iso" => "PL", "name" => "Polonia"],
                    ["iso" => "PT", "name" => "Portugal"],
                    ["iso" => "UK", "name" => "Reino Unido"],
                    ["iso" => "CZ", "name" => "República Checa"],
                    ["iso" => "RO", "name" => "Rumanía"],
                    ["iso" => "RU", "name" => "Rusia"],
                    ["iso" => "SM", "name" => "San Marino"],
                    ["iso" => "SE", "name" => "Suecia"],
                    ["iso" => "CH", "name" => "Suiza"],
                    ["iso" => "TR", "name" => "Turquía"],
                    ["iso" => "UA", "name" => "Ucrania"],
                    ["iso" => "YU", "name" => "Yugoslavia"],
                ],
            ],

            [
                'iso' => 'africa',
                'name' => "África",
                'countries' => [
                    ["iso" => "AO", "name" => "Angola"],
                    ["iso" => "DZ", "name" => "Argelia"],
                    ["iso" => "BJ", "name" => "Benín"],
                    ["iso" => "BW", "name" => "Botswana"],
                    ["iso" => "BF", "name" => "Burkina Faso"],
                    ["iso" => "BI", "name" => "Burundi"],
                    ["iso" => "CM", "name" => "Camerún"],
                    ["iso" => "CV", "name" => "Cabo Verde"],
                    ["iso" => "TD", "name" => "Chad"],
                    ["iso" => "KM", "name" => "Comores"],
                    ["iso" => "CG", "name" => "Congo"],
                    ["iso" => "CD", "name" => "Congo, República Democrática del"],
                    ["iso" => "CI", "name" => "Costa de Marfil"],
                    ["iso" => "EG", "name" => "Egipto"],
                    ["iso" => "ER", "name" => "Eritrea"],
                    ["iso" => "ET", "name" => "Etiopía"],
                    ["iso" => "GA", "name" => "Gabón"],
                    ["iso" => "GM", "name" => "Gambia"],
                    ["iso" => "GH", "name" => "Ghana"],
                    ["iso" => "GN", "name" => "Guinea"],
                    ["iso" => "GW", "name" => "Guinea Bissau"],
                    ["iso" => "GQ", "name" => "Guinea Ecuatorial"],
                    ["iso" => "KE", "name" => "Kenia"],
                    ["iso" => "LS", "name" => "Lesoto"],
                    ["iso" => "LR", "name" => "Liberia"],
                    ["iso" => "LY", "name" => "Libia"],
                    ["iso" => "MG", "name" => "Madagascar"],
                    ["iso" => "MW", "name" => "Malawi"],
                    ["iso" => "ML", "name" => "Malí"],
                    ["iso" => "MA", "name" => "Marruecos"],
                    ["iso" => "MU", "name" => "Mauricio"],
                    ["iso" => "MR", "name" => "Mauritania"],
                    ["iso" => "MZ", "name" => "Mozambique"],
                    ["iso" => "NA", "name" => "Namibia"],
                    ["iso" => "NE", "name" => "Níger"],
                    ["iso" => "NG", "name" => "Nigeria"],
                    ["iso" => "CF", "name" => "República Centroafricana"],
                    ["iso" => "ZA", "name" => "República de Sudáfrica"],
                    ["iso" => "RW", "name" => "Ruanda"],
                    ["iso" => "EH", "name" => "Sahara Occidental"],
                    ["iso" => "ST", "name" => "Santo Tomé y Príncipe"],
                    ["iso" => "SN", "name" => "Senegal"],
                    ["iso" => "SC", "name" => "Seychelles"],
                    ["iso" => "SL", "name" => "Sierra Leona"],
                    ["iso" => "SO", "name" => "Somalia"],
                    ["iso" => "SD", "name" => "Sudán"],
                    ["iso" => "SS", "name" => "Sudán del Sur"],
                    ["iso" => "SZ", "name" => "Suazilandia"],
                    ["iso" => "TZ", "name" => "Tanzania"],
                    ["iso" => "TG", "name" => "Togo"],
                    ["iso" => "TN", "name" => "Túnez"],
                    ["iso" => "UG", "name" => "Uganda"],
                    ["iso" => "DJ", "name" => "Yibuti"],
                    ["iso" => "ZM", "name" => "Zambia"],
                    ["iso" => "ZW", "name" => "Zimbabue"],
                ],
            ],

            [
                'iso' => 'oceania',
                'name' => "Oceanía",
                'countries' => [
                    ["iso" => "AU", "name" => "Australia"],
                    ["iso" => "FM", "name" => "Micronesia, Estados Federados de"],
                    ["iso" => "FJ", "name" => "Fiji"],
                    ["iso" => "KI", "name" => "Kiribati"],
                    ["iso" => "MH", "name" => "Islas Marshall"],
                    ["iso" => "SB", "name" => "Islas Salomón"],
                    ["iso" => "NR", "name" => "Nauru"],
                    ["iso" => "NZ", "name" => "Nueva Zelanda"],
                    ["iso" => "PW", "name" => "Palaos"],
                    ["iso" => "PG", "name" => "Papúa Nueva Guinea"],
                    ["iso" => "WS", "name" => "Samoa"],
                    ["iso" => "TO", "name" => "Tonga"],
                    ["iso" => "TV", "name" => "Tuvalu"],
                    ["iso" => "VU", "name" => "Vanuatu"],
                ],
            ],

            [
                'iso' => 'sudamerica',
                'name' => "Sudamérica",
                'countries' => [
                    ["iso" => "AR", "name" => "Argentina"],
                    ["iso" => "BO", "name" => "Bolivia"],
                    ["iso" => "BR", "name" => "Brasil"],
                    ["iso" => "CL", "name" => "Chile"],
                    ["iso" => "CO", "name" => "Colombia"],
                    ["iso" => "EC", "name" => "Ecuador"],
                    ["iso" => "GY", "name" => "Guayana"],
                    ["iso" => "PY", "name" => "Paraguay"],
                    ["iso" => "PE", "name" => "Perú"],
                    ["iso" => "SR", "name" => "Surinam"],
                    ["iso" => "TT", "name" => "Trinidad y Tobago"],
                    ["iso" => "UY", "name" => "Uruguay"],
                    ["iso" => "VE", "name" => "Venezuela"],
                ],
            ],

            [
                'iso' => 'norteamerica',
                'name' => "Norteamérica y Centroamérica",
                'countries' => [
                    ["iso" => "AG", "name" => "Antigua y Barbuda"],
                    ["iso" => "BS", "name" => "Bahamas"],
                    ["iso" => "BB", "name" => "Barbados"],
                    ["iso" => "BZ", "name" => "Belice"],
                    ["iso" => "CA", "name" => "Canadá"],
                    ["iso" => "CR", "name" => "Costa Rica"],
                    ["iso" => "CU", "name" => "Cuba"],
                    ["iso" => "DM", "name" => "Dominica"],
                    ["iso" => "SV", "name" => "El Salvador"],
                    ["iso" => "US", "name" => "Estados Unidos"],
                    ["iso" => "GD", "name" => "Granada"],
                    ["iso" => "GT", "name" => "Guatemala"],
                    ["iso" => "HT", "name" => "Haití"],
                    ["iso" => "HN", "name" => "Honduras"],
                    ["iso" => "JM", "name" => "Jamaica"],
                    ["iso" => "MX", "name" => "México"],
                    ["iso" => "NI", "name" => "Nicaragua"],
                    ["iso" => "PA", "name" => "Panamá"],
                    ["iso" => "PR", "name" => "Puerto Rico"],
                    ["iso" => "DO", "name" => "República Dominicana"],
                    ["iso" => "KN", "name" => "San Cristóbal y Nieves"],
                    ["iso" => "VC", "name" => "San Vicente y Granadinas"],
                    ["iso" => "LC", "name" => "Santa Lucía"],
                ],
            ],

            [
                'iso' => 'asia',
                'name' => "Asia",
                'countries' => [
                    ["iso" => "AF", "name" => "Afganistán"],
                    ["iso" => "SA", "name" => "Arabia Saudí"],
                    ["iso" => "BH", "name" => "Baréin"],
                    ["iso" => "BD", "name" => "Bangladesh"],
                    ["iso" => "MM", "name" => "Birmania"],
                    ["iso" => "BT", "name" => "Bután"],
                    ["iso" => "BN", "name" => "Brunéi"],
                    ["iso" => "KH", "name" => "Camboya"],
                    ["iso" => "CN", "name" => "China"],
                    ["iso" => "KP", "name" => "Corea, República Popular Democrática de"],
                    ["iso" => "KR", "name" => "Corea, República de"],
                    ["iso" => "AE", "name" => "Emiratos Árabes Unidos"],
                    ["iso" => "PH", "name" => "Filipinas"],
                    ["iso" => "IN", "name" => "India"],
                    ["iso" => "ID", "name" => "Indonesia"],
                    ["iso" => "IQ", "name" => "Iraq"],
                    ["iso" => "IR", "name" => "Irán"],
                    ["iso" => "IL", "name" => "Israel"],
                    ["iso" => "JP", "name" => "Japón"],
                    ["iso" => "JO", "name" => "Jordania"],
                    ["iso" => "KZ", "name" => "Kazajistán"],
                    ["iso" => "KG", "name" => "Kirguizistán"],
                    ["iso" => "KW", "name" => "Kuwait"],
                    ["iso" => "LA", "name" => "Laos"],
                    ["iso" => "LB", "name" => "Líbano"],
                    ["iso" => "MY", "name" => "Malasia"],
                    ["iso" => "MV", "name" => "Maldivas"],
                    ["iso" => "MN", "name" => "Mongolia"],
                    ["iso" => "NP", "name" => "Nepal"],
                    ["iso" => "OM", "name" => "Omán"],
                    ["iso" => "PK", "name" => "Paquistán"],
                    ["iso" => "QA", "name" => "Qatar"],
                    ["iso" => "SG", "name" => "Singapur"],
                    ["iso" => "SY", "name" => "Siria"],
                    ["iso" => "LK", "name" => "Sri Lanka"],
                    ["iso" => "TJ", "name" => "Tayikistán"],
                    ["iso" => "TH", "name" => "Tailandia"],
                    ["iso" => "TP", "name" => "Timor Oriental"],
                    ["iso" => "TM", "name" => "Turkmenistán"],
                    ["iso" => "UZ", "name" => "Uzbekistán"],
                    ["iso" => "VN", "name" => "Vietnam"],
                    ["iso" => "YE", "name" => "Yemen"],
                ],
            ],
        ];
    }

    /**
     * @param string $iso
     * @return array|string[]
     */
    public function findCountryByISO(string $iso): array
    {
        foreach ($this->getCountries() as $item) {
            foreach ($item['countries'] as $country) {
                if ($country['iso'] == $iso) {
                    return [$country['iso'], $country['name']];
                }
            }
        }

        return ['', ''];
    }

}
